<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClientesSeeder extends Seeder
{
    /**
     * Run the database seeds - DATOS REALES DEL SQL DE PRODUCCIÓN
     */
    public function run(): void
    {
        // Datos exactos del backup systemVentas.sql
        $clientes = [
            ['id' => 1, 'codigo_cliente' => 'CLI-001', 'nombre_completo' => 'MARÍA GONZÁLEZ LOPEZ', 'tipo_cliente' => 'PERSONA', 'ci_nit' => '12345678', 'telefono' => '70123456', 'email' => 'maria.gonzalez@email.com', 'direccion' => 'Av. Banzer #123, Zona Norte', 'colegio_id' => 2, 'nacionalidad' => 'Bolivia', 'departamento' => 'Santa Cruz', 'observaciones' => null, 'activo' => true, 'fecha_registro' => '2025-09-15 10:00:00'],
            ['id' => 2, 'codigo_cliente' => 'CLI-002', 'nombre_completo' => 'COLEGIO SAN ANDRÉS', 'tipo_cliente' => 'INSTITUCION', 'ci_nit' => '1023456789012', 'telefono' => '33456789', 'email' => 'administracion@sanandres.edu.bo', 'direccion' => 'Zona Norte, Calle Principal #456', 'colegio_id' => 2, 'nacionalidad' => 'Bolivia', 'departamento' => 'Santa Cruz', 'observaciones' => null, 'activo' => true, 'fecha_registro' => '2025-09-20 14:00:00'],
            ['id' => 3, 'codigo_cliente' => 'CLI-003', 'nombre_completo' => 'PEDRO MAMANI QUISPE', 'tipo_cliente' => 'PERSONA', 'ci_nit' => '87654321', 'telefono' => '70789456', 'email' => 'pedro.mamani@gmail.com', 'direccion' => 'Villa 1ro de Mayo, UV-25', 'colegio_id' => 4, 'nacionalidad' => 'Bolivia', 'departamento' => 'Santa Cruz', 'observaciones' => null, 'activo' => true, 'fecha_registro' => '2025-09-25 16:00:00'],
            ['id' => 4, 'codigo_cliente' => 'CLI-004', 'nombre_completo' => 'UNIDAD EDUCATIVA SANTA ROSA', 'tipo_cliente' => 'INSTITUCION', 'ci_nit' => '2034567890123', 'telefono' => '33789123', 'email' => 'secretaria@santarosa.edu.bo', 'direccion' => 'Barrio Las Flores #789', 'colegio_id' => 3, 'nacionalidad' => 'Bolivia', 'departamento' => 'Santa Cruz', 'observaciones' => null, 'activo' => true, 'fecha_registro' => '2025-09-28 09:00:00'],
            ['id' => 5, 'codigo_cliente' => 'CLI-005', 'nombre_completo' => 'ANA QUISPE FLORES', 'tipo_cliente' => 'PERSONA', 'ci_nit' => '45678912', 'telefono' => '75987654', 'email' => 'ana.quispe@gmail.com', 'direccion' => 'Plan 3000, UV-45, Mz-12', 'colegio_id' => 5, 'nacionalidad' => 'Bolivia', 'departamento' => 'Santa Cruz', 'observaciones' => null, 'activo' => true, 'fecha_registro' => '2025-10-01 11:00:00'],
            ['id' => 6, 'codigo_cliente' => 'CLI-006', 'nombre_completo' => 'ROBERTO VILLARROEL MENDEZ', 'tipo_cliente' => 'PERSONA', 'ci_nit' => '78912345', 'telefono' => '75987654', 'email' => 'roberto.villarroel@gmail.com', 'direccion' => 'Zona Centro, Calle Warnes', 'colegio_id' => 1, 'nacionalidad' => 'Bolivia', 'departamento' => 'Santa Cruz', 'observaciones' => null, 'activo' => true, 'fecha_registro' => '2025-10-02 15:00:00'],
            ['id' => 7, 'codigo_cliente' => 'CLI-007', 'nombre_completo' => 'PEÑA  PRUEBA', 'tipo_cliente' => 'INSTITUCION', 'ci_nit' => '99999999', 'telefono' => '756784528', 'email' => 'cliente2pruebaa@gmail.com', 'direccion' => 'calle España', 'colegio_id' => 1, 'nacionalidad' => 'Bolivia', 'departamento' => 'Santa Cruz', 'observaciones' => null, 'activo' => true, 'fecha_registro' => '2025-10-25 09:36:22'],
            ['id' => 8, 'codigo_cliente' => 'CLI-008', 'nombre_completo' => 'LUIS MARIO', 'tipo_cliente' => 'PERSONA', 'ci_nit' => '2131231', 'telefono' => '23123123', 'email' => 'luisrochavela1@gmail.com', 'direccion' => '132ewwerwerewr', 'colegio_id' => 2, 'nacionalidad' => 'Bolivia', 'departamento' => 'Santa Cruz', 'observaciones' => null, 'activo' => true, 'fecha_registro' => '2025-10-25 09:53:47'],
            ['id' => 9, 'codigo_cliente' => 'CLI-009', 'nombre_completo' => 'MIGUEL ANGEL PINTO ARAMAYO', 'tipo_cliente' => 'INSTITUCION', 'ci_nit' => '', 'telefono' => '72112703', 'email' => 'pintoaramayomiguelangel@gmail.com', 'direccion' => '', 'colegio_id' => 6, 'nacionalidad' => 'Bolivia', 'departamento' => 'Santa Cruz', 'observaciones' => null, 'activo' => true, 'fecha_registro' => '2025-10-25 10:51:26'],
            ['id' => 10, 'codigo_cliente' => 'CLI-010', 'nombre_completo' => 'MAURICIO VASQUEZ MENACHO', 'tipo_cliente' => 'PERSONA', 'ci_nit' => '11329595', 'telefono' => '74181117', 'email' => 'mauriciovasquezmenacho@gmail.com', 'direccion' => 'av. banzer', 'colegio_id' => 1, 'nacionalidad' => 'Bolivia', 'departamento' => 'Santa Cruz', 'observaciones' => null, 'activo' => true, 'fecha_registro' => '2025-10-28 10:31:25'],
            ['id' => 11, 'codigo_cliente' => 'CLI-011', 'nombre_completo' => 'PEÑA PRUEBA 2', 'tipo_cliente' => 'PERSONA', 'ci_nit' => '14067067', 'telefono' => '75678428', 'email' => 'cliente3pruebaa@gmail.com', 'direccion' => 'Santa Cruz', 'colegio_id' => 1, 'nacionalidad' => 'Bolivia', 'departamento' => 'Santa Cruz', 'observaciones' => null, 'activo' => true, 'fecha_registro' => '2025-10-31 15:30:17'],
            ['id' => 12, 'codigo_cliente' => 'CLI-012', 'nombre_completo' => 'JOSE DAVID COLQUE BERNABE', 'tipo_cliente' => 'INSTITUCION', 'ci_nit' => '', 'telefono' => '77686714', 'email' => 'jcolqueberbabe@gmail.com', 'direccion' => '3er anillo', 'colegio_id' => 7, 'nacionalidad' => 'Bolivia', 'departamento' => 'Santa Cruz', 'observaciones' => null, 'activo' => true, 'fecha_registro' => '2025-11-08 09:03:04'],
            ['id' => 13, 'codigo_cliente' => 'CLI-013', 'nombre_completo' => 'JOSE DAVID COLQUE BERNABE', 'tipo_cliente' => 'INSTITUCION', 'ci_nit' => '', 'telefono' => '77686714', 'email' => 'jcolqueberbabe@gmail.com', 'direccion' => '3er anillo', 'colegio_id' => 7, 'nacionalidad' => 'Bolivia', 'departamento' => 'Santa Cruz', 'observaciones' => null, 'activo' => true, 'fecha_registro' => '2025-11-08 09:03:17'],
            ['id' => 14, 'codigo_cliente' => 'CLI-014', 'nombre_completo' => 'Pruaba SR1', 'tipo_cliente' => 'INSTITUCION', 'ci_nit' => '14067098', 'telefono' => '7777777', 'email' => 'cliente2pruebaa@gmail.com', 'direccion' => '3015', 'colegio_id' => 2, 'nacionalidad' => 'Bol', 'departamento' => 'Santa Cruz', 'observaciones' => 'Pruaba SR1', 'activo' => true, 'fecha_registro' => '2025-11-20 01:27:10'],
            ['id' => 15, 'codigo_cliente' => 'CLI-015', 'nombre_completo' => 'PRUEBA SR INTERFAZ', 'tipo_cliente' => 'PERSONA', 'ci_nit' => '33333333', 'telefono' => '756784528', 'email' => 'cliente2pruebaa@gmail.com', 'direccion' => 'calle España', 'colegio_id' => 1, 'nacionalidad' => 'Bolivia', 'departamento' => 'Santa Cruz', 'observaciones' => 'Prueba SR Desde la interfaz', 'activo' => true, 'fecha_registro' => '2025-11-20 01:43:34'],
            ['id' => 16, 'codigo_cliente' => 'CLI-016', 'nombre_completo' => 'Prueba SR2', 'tipo_cliente' => 'INSTITUCION', 'ci_nit' => '778787878', 'telefono' => '78787878', 'email' => 'cliente2pruebaa@gmail.com', 'direccion' => '2002', 'colegio_id' => 2, 'nacionalidad' => 'SIV', 'departamento' => 'Cochabamba', 'observaciones' => 'Pruena del excel para el SR 2', 'activo' => true, 'fecha_registro' => '2025-11-20 02:01:00'],
            ['id' => 17, 'codigo_cliente' => 'CLI-017', 'nombre_completo' => 'MARTA ADORNO', 'tipo_cliente' => 'PERSONA', 'ci_nit' => '', 'telefono' => '75338022', 'email' => 'martadorno2@gmail.com', 'direccion' => 'Col La Salle', 'colegio_id' => 2, 'nacionalidad' => 'Bolivia', 'departamento' => 'Santa Cruz', 'observaciones' => 'Libros', 'activo' => true, 'fecha_registro' => '2025-11-21 18:05:48'],
            ['id' => 18, 'codigo_cliente' => 'CLI-018', 'nombre_completo' => 'SANDRA SANDOVAL MONTAÑO', 'tipo_cliente' => 'PERSONA', 'ci_nit' => '4834855', 'telefono' => '70900027', 'email' => 'drasandralsm@gmail.com', 'direccion' => 'Col La Salle', 'colegio_id' => 2, 'nacionalidad' => 'Bolivia', 'departamento' => 'Santa Cruz', 'observaciones' => 'Venta de materiales', 'activo' => true, 'fecha_registro' => '2025-11-21 21:51:48'],
            // Datos adicionales para cumplir con el mínimo de 20
            ['id' => 19, 'codigo_cliente' => 'CLI-019', 'nombre_completo' => 'CARLOS MONTENEGRO PEREZ', 'tipo_cliente' => 'PERSONA', 'ci_nit' => '9876543', 'telefono' => '71234567', 'email' => 'carlos.montenegro@gmail.com', 'direccion' => 'Av. Santos Dumont, Zona Norte', 'colegio_id' => 3, 'nacionalidad' => 'Bolivia', 'departamento' => 'Santa Cruz', 'observaciones' => null, 'activo' => true, 'fecha_registro' => '2025-11-22 10:00:00'],
            ['id' => 20, 'codigo_cliente' => 'CLI-020', 'nombre_completo' => 'INSTITUTO BOLIVIANO', 'tipo_cliente' => 'INSTITUCION', 'ci_nit' => '3045678901234', 'telefono' => '33112233', 'email' => 'contacto@institutoboliviano.edu.bo', 'direccion' => 'Plan 3000, Mz-45', 'colegio_id' => 5, 'nacionalidad' => 'Bolivia', 'departamento' => 'Santa Cruz', 'observaciones' => 'Compra institucional', 'activo' => true, 'fecha_registro' => '2025-11-23 14:30:00'],
        ];

        DB::table('clientes')->insert($clientes);
    }
}
