@extends('layouts.admin')

@section('title', 'Calendario Académico')

@section('css')
    <link rel="stylesheet" href="{{ asset('css/admin/calendario/index.css') }}">
@endsection

@section('content')
<div class="calendario-container">
    <div class="control-panel">
        <div class="panel-header">
            <div class="header-title">
                <div class="icon-wrapper">
                    <i class="fas fa-calendar-alt"></i>
                </div>
                <div class="title-content">
                    <h2>Calendario Académico</h2>
                    <span class="subtitle">Gestión de eventos y fechas importantes</span>
                </div>
            </div>
            <div class="header-actions">
                <button class="btn-primary-action" id="btnNewEvent">
                    <i class="fas fa-plus"></i>
                    <span>Nuevo Evento</span>
                </button>
            </div>
        </div>

        <div class="calendar-controls">
            <button class="btn-nav" id="prevMonth"><i class="fas fa-chevron-left"></i></button>
            <h3 class="current-month" id="currentMonthDisplay">Diciembre 2025</h3>
            <button class="btn-nav" id="nextMonth"><i class="fas fa-chevron-right"></i></button>
            <button class="btn-today" id="btnToday">Hoy</button>
        </div>
    </div>

    <div class="calendar-layout">
        <div class="calendar-grid">
            <div class="weekdays">
                <div>Dom</div>
                <div>Lun</div>
                <div>Mar</div>
                <div>Mié</div>
                <div>Jue</div>
                <div>Vie</div>
                <div>Sáb</div>
            </div>
            <div class="days" id="calendarDays">
                <!-- Days will be generated by JS -->
            </div>
        </div>

        <div class="upcoming-events">
            <h3>Próximos Eventos</h3>
            <div class="event-list" id="upcomingEventsList">
                <div class="event-item">
                    <div class="event-date">
                        <span class="day">15</span>
                        <span class="month">DIC</span>
                    </div>
                    <div class="event-info">
                        <h4>Entrega de Notas</h4>
                        <span class="event-badge academic">Académico</span>
                    </div>
                </div>
                <!-- Mock events -->
                <div class="event-item">
                    <div class="event-date">
                        <span class="day">20</span>
                        <span class="month">DIC</span>
                    </div>
                    <div class="event-info">
                        <h4>Fin de Semestre</h4>
                        <span class="event-badge holiday">Feriado</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal Nuevo Evento (Hidden by default) -->
<!-- Can be implemented later or now depending on scope. For index visual, not strictly required but good to have skeleton -->
@endsection

@section('js')
    <script src="{{ asset('js/admin/calendario/index.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
@endsection